SELECT TENDEAN, CAST(SUM(THOIGIAN) AS DECIMAL(6,2)) AS 'TONG_GIO_LAM'
FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT TENDEAN, CAST(SUM(THOIGIAN) AS VARCHAR) AS 'TONG_GIO_LAM'
FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT TENPHG, CAST(AVG(LUONG) AS DECIMAL(8,2)) AS 'GIO_LAM_TRUNG_BINH'
FROM NHANVIEN
INNER JOIN PHONGBAN ON NHANVIEN.PHG = PHONGBAN.MAPHG
GROUP BY TENPHG

SELECT TENDEAN, CEILING(SUM(THOIGIAN)) AS 'TONG_GIO_LAM'
FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT TENDEAN, FLOOR(SUM(THOIGIAN)) AS 'TONG_GIO_LAM'
FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT TENDEAN, ROUND(SUM(THOIGIAN), 2) AS 'TONG_GIO_LAM'
FROM CONGVIEC
INNER JOIN DEAN ON CONGVIEC.MADA = DEAN.MADA
INNER JOIN PHANCONG ON CONGVIEC.MADA = PHANCONG.MADA
GROUP BY TENDEAN

SELECT HONV, TENLOT, TENNV, ROUND(SUM(LUONG), 2) AS 'GIO_LAM_TRUNG_BINH'
FROM NHANVIEN
GROUP BY HONV, TENLOT, TENNV, PHG
HAVING PHG = 5

SELECT UPPER(HONV) AS HONV, LOWER(TENLOT) AS TENLOT,
REPLACE(LOWER(TENNV), SUBSTRING(TENNV, 2, 1), UPPER(SUBSTRING(TENNV, 2, 1))) AS TENNV
FROM NHANVIEN
GROUP BY HONV, TENLOT, TENNV