CREATE PROC XINCHAO
@TEN NVARCHAR (20)
AS
BEGIN
PRINT N'XIN CHÀO ' + @TEN;
END
EXEC XINCHAO N'NHÓM 2'
GO

CREATE PROC TONG
@S1 INT , @S2 INT
AS
DECLARE @TG INT
SET @TG = @S1+@S2
PRINT CONCAT ('TONG LA:' , @TG)
EXEC TONG 4,5
GO

CREATE PROC TONGSOCHAN
@N INT 
AS
DECLARE @TONG INT = 0,@DEM INT =2;
WHILE @DEM<@N
BEGIN
SET @TONG=@TONG+@DEM
SET @DEM=@DEM+2
END
PRINT'TONG' + CAST (@TONG AS VARCHAR(4))
EXEC TONGSOCHAN 8
GO

CREATE PROC UOCCHUNG
@A INT ,@B INT 
AS
WHILE (@A!=@B)
IF(@A>@B)
SET @A-=@B
ELSE
SET @B-=@A
RETURN @A
DECLARE @C INT 
EXEC @C=UOCCHUNG 30,40
SELECT @C 

GO
CREATE PROC THONGTINNV
	@MANV nvarchar(9)
AS
BEGIN
	SELECT * FROM NHANVIEN
	WHERE MANV = @MANV
END

GO
CREATE PROC LAB5_2_B 
	@MANV INT
AS
BEGIN
	select count(MANV) as 'so luong', MADA, TENPHG from NHANVIEN
	inner join PHONGBAN on NHANVIEN.PHG = PHONGBAN.MAPHG
	inner join DEAN on DEAN.PHONG = PHONGBAN.MAPHG
	where MADA = @MANV
	group by TENPHG,MADA
END
EXEC LAB5_2_B 10

GO
CREATE PROC LAB5_2_C
	@MANV INT
AS
BEGIN
	select count(MANV)as 'so luong', MADA, TENPHG from NHANVIEN
	inner join PHONGBAN on NHANVIEN.PHG = PHONGBAN.MAPHG
	inner join DEAN on DEAN.PHONG = PHONGBAN.MAPHG
	where MADA = 2 and DDIEM_DA = 'Nha Trang'
group by TENPHG,MADA
END
EXEC LAB5_2_C 10

GO
CREATE PROC LAB5_2_D 
	@MATP varchar(9)
AS
BEGIN
	select HONV, TENNV, TENPHG, NHANVIEN.MANV, THANNHAN.*
	from NHANVIEN
	inner join PHONGBAN on PHONGBAN.MAPHG = NHANVIEN.PHG
	left outer join THANNHAN on THANNHAN.MA_NVIEN = NHANVIEN.MANV
	where THANNHAN.MA_NVIEN is null and TRPHG = @MATP
END

EXEC LAB5_2_D '008'

GO
CREATE PROC LAB5_2_E @MANV varchar(9)
,@MAPB varchar(9)
AS
BEGIN
	IF exists(select * from NHANVIEN where MANV = '001' and PHG = @MAPB)
		print 'Nhan vien: ' + @MANV + ' co trong phong ban: ' + @MAPB
	ELSE 
		print 'Nhan vien: ' + @MANV + ' khong co trong phong ban: ' + @MAPB
END

EXEC LAB5_2_E '001','5'

GO
CREATE PROC LAB5_3_A @MAPB INT, @TENPB nvarchar(20),
@MATP varchar(10), @NGAYNHANCHUC DATE
AS
BEGIN
	IF(exists(select * from PHONGBAN where MaPHG=@MAPB))
		print 'Them that bai'
	ELSE 
		BEGIN
			insert into PHONGBAN(MAPHG, TENPHG, TRPHG, NG_NHANCHUC)
			values (@MAPB, @TENPB, @MATP, @NgayNhanChuc)
			print 'Them thanh cong'
		END
END

EXEC LAB5_3_A '7','CNTT','008','2002-07-28'